---
# vars file for aws-create-ec2
aws_region: "{{ aws_region_choice | default('us-east-1') }}"

# Instance variables 
ec2_instance_type: "{{ ec2_type_choice | default('t2.micro') }}" 
ec2_instance_count: "{{ virtualmachine_count_choice | default(1) }}"
ec2_volume_size: "{{ ec2_volume_size_choice | default(30) }}" 
ec2_keypair_name: "{{ stat_keypair_name | default('Ansible_Created_Keypair') }}"

#SG
ec2_security_group: "{{ stat_sg_id | default('') }}"

#Instance Tags
ec2_name_tag: "{{ ec2_name_tag_choice | default('Ansible_Created_EC2') }}"
ec2_provisioner_tag: "{{ ec2_provisioner_tag_choice | default('Ansible') }}"
ec2_created_tag: "{{ ec2_created_tag_choice | default(ansible_date_time.date) }}"

ec2_virtualmachine_ostype: "{{ virtualmachine_ostype_choice | default('Linux') }}"