---
# tasks file for aws-create-ec2

#- name: Provision EC2 Instance
  #include_tasks: create_ec2_instane.yml
- name: Including {{ ec2_virtualmachine_ostype }} Specific Variables
  include_vars: "{{ ec2_virtualmachine_ostype }}.yml"

- name: setting fact if multicloud var is set
  set_fact:
    ec2_name_tag: "{{ virtualmachine_name_choice }}"
  when: virtualmachine_name_choice is defined

- name: Provision EC2 instance(s)
  ec2_instance:
    name: "{{ short_name }}"
    region: "{{ aws_region }}"
    instance_type: "{{ ec2_instance_type }}"
    image_id: "{{ ec2_ami_id }}"
    network:
      assign_public_ip: true
    vpc_subnet_id: "{{ subnet_name }}"
    key_name: "{{ keypair_name }}"
    wait: yes
    volumes:
      - device_name: /dev/sda1
        ebs.volume_type: gp2
        ebs.volume_size: "{{ ec2_volume_size }}"
        delete_on_termination: true
    security_group: "{{ ec2_security_group }}"
#    tags:
#      Name: "{{ ec2_name_tag }}"
#      Name: "{{ virtualmachine_name_choice if (virtualmachine_name_choice is defined and virtualmachine_name_choice != '') else ec2_name_tag }}"
#     Provisioner: "{{ ec2_provisioner_tag }}"
#      Created: "{{ ec2_created_tag }}"
#    user_data: "{{ lookup('template', ec2_userdata_template_file_name) }}"
    #exact_count: "{{ ec2_instance_count }}"
    #count_tag: 
    #  Name: "{{ virtualmachine_name_choice if (virtualmachine_name_choice is defined) else ec2_name_tag }}"
    #  Provisioner: "{{ ec2_provisioner_tag }}"
    #  Created: "{{ ec2_created_tag }}"
  register: ec2

- name: Wait for connection to come up
  wait_for: 
    host: "{{ item.public_ip }}" 
    port: "{{ wait_for_port }}" 
    state: started
  with_items: "{{ ec2.instances }}"
